// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";

// 1. Setup Montserrat for Headings
const montserrat = Montserrat({ 
  subsets: ["latin"], 
  weight: ["300", "700", "900"],
  variable: "--font-heading" // This variable is used in globals.css
});

// 2. Setup Poppins for Body text
const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["300", "400", "600"],
  variable: "--font-body" // This variable is used in globals.css
});

export const metadata = {
  title: "Faraz | Full Stack Developer",
  description: "Portfolio of Faraz, a MERN Stack Developer.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        {/* FontAwesome for Icons */}
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet" />
      </head>
      {/* 3. Inject Font Variables */}
      <body className={`${montserrat.variable} ${poppins.variable} font-sans antialiased selection:bg-accent selection:text-black`}>
        {children}
      </body>
    </html>
  );
}